rtCamp/nginx-helper

.gitignore, nginx-helper.php, wp-cli.php
=> WP_CLI Command added : Kickstarter

.travis.yml, tests/functional/src/purge-method-get-request-page-test.js, tests/functional/src/purge-method-unlink-files-page-test.js
Fixed Travis CI failing issue for Fastcgi Cache tests.
=> End to End Testing: Fastcgi Cache Test Script

README.md, admin/admin.php, admin/lib/nginx-general.php, includes/redis-delete.php, nginx-helper.php, readme.txt, redis-purger.php
- Added PhpRedis API support.
- Fixed cache purging link in admin bar.
=> Enhancement and Fixed Issues.

admin/admin.php, admin/assets/nginx.js, nginx-helper.php
See: https://github.com/rtCamp/nginx-helper/issues/68
=> Use WP Ajax to get latest news

admin/partials/nginx-helper-general-options.php
=> Remove extra spacing for nginx map section

admin/partials/nginx-helper-general-options.php
=> Fix an issue where custom purge url option does not show newlines when using multiple urls

README.md, nginx-helper.php, readme.txt
Add change log for version 2.0.2
=> Bump plugin version and update readme files

admin/class-nginx-helper-admin.php
=> Check against boolean value instead of string

.github/main.workflow
- Update workflow to run on create event
- Add vendor dir to exclude list
=> Update workflow to run on create event

admin/class-nginx-helper-admin.php
Fixes https://github.com/rtCamp/nginx-helper/issues/199
=> Fix header key comparison

includes/class-nginx-helper.php
=> Hide Purge Cache button in admin bar when purge is disabled

admin/class-phpredis-purger.php, admin/class-predis-purger.php
Becasue home and site url could be different.
=> Use home_url() in custom purge URLs

README.md, admin/class-fastcgi-purger.php, admin/class-purger.php
- Update function doc of new Hooks for FastCGI cache
=> Add inline document for new actions for FastCGI cache

admin/css/nginx-helper-admin.css, admin/icons/css/nginx-fontello.css, admin/partials/nginx-helper-sidebar-display.php, admin/partials/nginx-helper-support-options.php
- Update free and premium support links
- Remove old and invalid social links from plugin settings sidebar
=> Update support and contact links

includes/class-nginx-helper.php
- Bump version to 2.2.0 in class initialization
=> Bump version to 2.2.0 in class initialization

admin/class-purger.php
- Fix FastCGI timeout on purge cache
- For: https://wordpress.org/support/topic/2-2-0-version-timeouts-on-purge-cache/
=> Fix timeout issue on FastCGI cache purge

admin/partials/nginx-helper-general-options.php
https://github.com/rtCamp/nginx-helper/issues/236
Added nonce for form verification.
=> Fixed issue for 'Save All Changes' value sent for button on form submit

README.md, readme.txt
=> Update ReadMe with FAQ link and Donate link

admin/class-purger.php
Fixed the issue [https://github.com/rtCamp/nginx-helper/issues/40](https://github.com/rtCamp/nginx-helper/issues/40)
=> [Issue 40] Fix: purge date archives for all public post types

admin/class-purger.php
Fixed the issue [Pages moved to trash does not get cleared #191](https://github.com/rtCamp/nginx-helper/issues/191)
=> Fixed Issue-191 (Pages and CPTs were not being cleared on moving to trash)

.github/ci/main.sh, .github/workflows/e2e-test.yml, README.md, admin/class-nginx-helper-admin.php, admin/class-purger.php, readme.txt, tests/e2e-playwright/bin/pr-status.js, tests/e2e-playwright/package-lock.json, tests/e2e-playwright/package.json, tests/e2e-playwright/playwright.config.ts
- Created `sync-dev-with-master` branch from develop (`git checkout -b sync-dev-with-master`)
- Pulled develop (`git pull origin develop`)
- Pulled master (`git pull origin master`)
- Pushed branch (`git push --set-upstream origin sync-dev-with-master`)
- Created PR.
=> Syncs develop branch with master

.github/workflows/create.yml
The aim of this PR is to update the GH action to use SVN_USERNAME and SVN_PASSWORD
- Build Update
- https://github.com/rtCamp/nginx-helper/issues/384
=> Update the GH Action to use SVN_USERNAME and SVN_PASSWORD

.github/workflows/create.yml
The aim of this PR is to update the GH action to replace SVN_USERNAME and SVN_PASSWORD with WORDPRESS_USERNAME and WORDPRESS_PASSWORD.
- Build Update
- https://github.com/rtCamp/nginx-helper/issues/384
=> Update the GH action to replace SVN_USERNAME and SVN_PASSWORD

.github/workflows/e2e-test.yml
Updated the version of the artifact `actions/upload-artifact@v1` to `actions/upload-artifact@v4`
=> Updated the Artifact Version

.github/workflows/e2e-test.yml
Updated the version of the artifact `actions/upload-artifact@v1` to `actions/upload-artifact@v4`
=> Updated the artifacts versions for main

README.md, readme.txt
The aim of this PR is to add props for the user stefanfisk for the PR #397
Documentation Update
https://github.com/rtCamp/nginx-helper/issues/396
=> Add Props for the PR #397

README.md, nginx-helper.php, readme.txt
Update the tested up to to version 6?8
=> Update tested upto version to 6.8

includes/class-nginx-helper.php
- Bump the plugin version to 2.3.5 in Nginx Helper Class
Ref: https://github.com/rtCamp/nginx-helper/issues/431
=> Bump the Plugin Version in Helper Class

admin/class-nginx-helper-admin.php, admin/partials/nginx-helper-general-options.php, includes/class-nginx-helper-activator.php, includes/class-nginx-helper-deactivator.php, includes/class-nginx-helper.php
This PR introduces an option in the Nginx Helper settings that lets administrators assign the **“Nginx Helper | Purge Cache”** capability to additional user roles (e.g., Editor, Author, or custom roles).
* By default, the capability remains restricted to Administrators (unchanged behavior).
* Admins can toggle checkboxes in the plugin settings to choose which roles can access the purge cache option in the admin bar.
* Internally, the plugin adds the capability to the selected roles.
Closes:- https://wordpress.org/support/topic/enable-purge-cache-option-in-admin-bar-for-user-role/
---
Currently, the purge cache capability is **hard-coded to Administrators only**. This is limiting because:
* Many site setups require non-admins (Editors, Content Managers, or custom roles) to manually purge …
=> Enable purge cache option in admin bar for user role [master]
