rtCamp/nginx-helper

admin/lib/nginx-general.php, purger.php
I needed to be able to purge cache files without using the [ngx_cache_purge](https://github.com/FRiCKLE/ngx_cache_purge) module. 
This pull request adds an option to the "Purge Options" area to allow the site admin to choose how cache files should be purged. The default option is to use a GET request to the /purge version of the URL, as required by ngx_cache_purge. The second option lets the plugin directly remove the cache files from the server.  
Screenshot of new option:
I followed information from [this article](https://www.digitalocean.com/community/tutorials/how-to-setup-fastcgi-caching-with-nginx-on-your-vps#purging-the-cache) to compute the correct cache file to delete. The URL to delete is hashed with md5 and then given a specific folder and file name based on that hash. 
In …
=> Added the option to purge cache files directly without ngx_cache_purge

admin/lib/nginx-general.php
The purge url was escaped, so the ampersand character (&) was encoded, converting the query string into a hashtag.
Signed-off-by: Javis Perez <javisperez@esd.com.do>
=> Bug fix - Can't purge because of bad url

admin/install.php
On new installations, I was getting this PHP Notice
`PHP Notice:  Undefined index: purge_method in /var/www/testwp.bvm.iamme.in/htdocs/wp-content/plugins/nginx-helper/purger.php on line 213`
To fix I just added 'purge_method' to be saved with the initial options.
=> Updated the initial settings to include the 'purge_method' 

purger.php, redis-purger.php
Hi all, for one of my plugins I needed a way to purge additional URLs along with normal page/post/taxonomy and feed URLs. The new option "Custom Purge URL" is useful but the URLs in my plugin can vary according to plugin settings which makes it too complicated for users to add them manually.
This hook allows the $purge_urls array to be altered or appended just before purging custom urls. The hook passes the array of custom urls and expects an array to be returned.
Note: I do not have a Redis server so only the changes to purger.php are tested. If anyone has a Redis server and time to test the changes, please let me know.
=> Create new filter hook for purge urls

nginx-helper.php
Doesn't make sense to show HTML comments in places that aren't necessarily HTML output
=> Don't add timestamp if cron or wpcli

purger.php, redis-purger.php
Added WPML support following erich_k4wp solution: https://wordpress.org/support/topic/wrong-homepage-cache-cleared-when-wpml-plugin-used
And changed the purge all function for redis. For this issue [https://github.com/rtCamp/nginx-helper/issues/113](url)
=> Add WPML Support + Change in Purge ALL with Redis. 

nginx-helper.php
wp_redirect should return true on success
The core WP function does this and it should for compatibility.
https://developer.wordpress.org/reference/functions/wp_redirect/
Uncovered in this issue with Redirection https://github.com/johngodley/redirection/issues/157
=> fix wp_redirect

redis-purger.php
Fixes redis purge-all feature, so it works for installations where wordpress lives in a separate folder.
See #129 for broader description
=> Fixes purge-all feature

README.md, admin/lib/nginx-general.php, includes/redis-delete.php, redis-purger.php
The goal is to allow defining Redis cache's host/port/prefix without using nginx helper's settings backend page. The three defines are:
```
RT_WP_NGINX_HELPER_REDIS_HOSTNAME
RT_WP_NGINX_HELPER_REDIS_PORT
RT_WP_NGINX_HELPER_REDIS_PREFIX
```
If not defined, everything works as is (fallback to the settings stored in options, if empty, fallback to 127.0.0.1/6379/nginx-cache:
If defined, the input fields for the predefined redis settings are disabled, with note underneath to inform the user this field is overridden by defines.
Documentation (FAQ in README.md) is updated to reflect this feature.
The main benefit of this is in multiple server situations (production vs staging, load balanced servers, etc) you don't have to rely on database to inform nginx helper about where to find the redis …
=> Allow override Redis host/port/prefix via defines

README.md, admin/class-fastcgi-purger.php, admin/class-nginx-helper-admin.php, admin/class-phpredis-purger.php, admin/class-predis-purger.php, admin/class-purger.php, admin/index.php, admin/js/nginx-helper-admin.js, admin/partials/nginx-helper-admin-display.php, admin/partials/nginx-helper-general-options.php, admin/partials/nginx-helper-sidebar-display.php, includes/class-nginx-helper-activator.php, includes/class-nginx-helper-deactivator.php, includes/class-nginx-helper-i18n.php, includes/class-nginx-helper-loader.php, includes/class-nginx-helper.php, includes/index.php, index.php, nginx-helper.php, phpcs.xml, readme.txt, uninstall.php, wp-cli.php
This PR contains below changes.
- Refactor code changes
- PHPCS issues and warnings resolving
- Missing code from master added
Below are some issues which need debugging.
- Redis cache flush on post update/ deletes not working.
- Timestamp shows latest time - Needs to check it's functionality or issue.
- Cache not found while deleting home page cache
`Purging homepage http://nhtest.h1.rtdemo.in/
2018-10-15 07:43:32  | ERROR | - Cache Not Found | http://nhtest.h1.rtdemo.in/`
=> PHPCS warning and error with refactoring

purger.php
Deleting a comment administratively wasn't triggering a purge. Cause is a status typo, $oldstatus == 'approve' should be 'approved'.
=> Fix typo causing failure to purge on trashed comment.

admin/class-nginx-helper-admin.php
On a multisite, using `admin_url` will link to main site's admin page. Use `network_admin_url` so it will link to network admin on a multisite, and on a single site it will link to normal admin page.
=> 👌 Use network_admin_url to get network correct settings url

admin/class-nginx-helper-admin.php
There is an undefined error when we install the plugin for the first time and if Redis is not available.
=> 🐛 Set default value for undefined variable

admin/class-purger.php
I have fixed the purge caching issue when the post status is changed to draft or pending.
I have used get_sample_permalink() to fix this issue because the get_permalink() returns URL something like https://example.com?p=6 and we need full permalink something like https://example.com/post-slug/
The get_permalink() function returns full permalink for the published post only. I explored WordPress codebase and found get_sample_permalink() which returns an array containing the sample permalink with a placeholder for the post name, and the post name.
Fixes #170
=> Fix the purge caching issue when the post status is changed to draft or pending

admin/class-nginx-helper-admin.php, includes/class-nginx-helper.php
I have fixed the Purge Cache menu caching issue in front-end.
I have changed the name of Purge Cache menu button in the front to 'Purge Current Page'
When the 'Purge Current Page' menu button on the front end is now clicked, it only clears the page cache.
Fixes #171
=> Fix Purge Cache menu caching issue in the front-end

admin/partials/nginx-helper-general-options.php
The existing links were going into infinite redirect loop, and not showing the article that its intended to do.
=> Correct the links for fastcgi cache purge

.github/main.workflow
Use GitHub action to release plugin. 
Ref: https://github.com/rtCamp/action-wp-org-plugin-deploy
When you are tagging the release please don't add `v` along with version_number.
`git tag -a 2.0.3 -m "Tagging Version 2.0.3"`
=> Add option to deploy plugin to WP.org using GitHub Actions

admin/class-fastcgi-purger.php, admin/class-phpredis-purger.php, admin/class-predis-purger.php, admin/class-purger.php
Add helpful actions and filters to extend plugin functionality
=> Add actions and filters

admin/class-purger.php
If logging has never been enabled, the `nginx.log` won't exist and `filesize()` will throw an exception.
=> Don't try to check the size of nginx.log if it doesn't exist

README.md, nginx-helper.php, readme.txt
* Add wildcard cache key deletion for device type cache purge. [#203](https://github.com/rtCamp/nginx-helper/pull/203) - by [pradeep910](https://github.com/pradeep910)
* Add filter `rt_nginx_helper_purge_url` to filter the URL to be purged. [#182](https://github.com/rtCamp/nginx-helper/pull/182) - by [todeveni](https://github.com/todeveni)
* Add filter `rt_nginx_helper_purge_cached_file` to filter the cached file name. [#182](https://github.com/rtCamp/nginx-helper/pull/182) - by [todeveni](https://github.com/todeveni)
* Add filter `rt_nginx_helper_remote_purge_url` to filter remote URL to be purged. [#182](https://github.com/rtCamp/nginx-helper/pull/182) - by [todeveni](https://github.com/todeveni)
* Add action `rt_nginx_helper_after_fastcgi_purge_all` to fire after the FastCGI cache has …
=> Version Update 2.1.0

admin/class-purger.php
There are a few locations in nginx-helper (dating back to at least 1.9.10) that were sending requests to `/purge/` even if cache purging was disabled in settings. On our environment, this was causing errors and unnecessary load on our infrastructure. My patch simply adds guard conditions to `Purger::purge_image_on_edit`, `Purger::purge_on_taxonomy_term_edited`, and `Purger::purge_on_check_ajax_referer`.
=> Plugged locations that were sending purge requests even if disabled

admin/class-nginx-helper-admin.php
=> Don't add Nginx timestamp on WP login page

README.md, languages/nginx-helper.po, nginx-helper.php, readme.txt
* Add filter `rt_nginx_helper_fastcgi_purge_suffix` to change purge suffix for FastCGI cache. [#141](https://github.com/rtCamp/nginx-helper/pull/141) - by [stayallive](https://github.com/stayallive)
* Add filter `rt_nginx_helper_fastcgi_purge_url_base` to change purge URL base for FastCGI cache. [#141](https://github.com/rtCamp/nginx-helper/pull/141) - by [stayallive](https://github.com/stayallive)
* Update our code to be in line with WordPress Coding standards in various places. [#209](https://github.com/rtCamp/nginx-helper/pull/209) - by [abhijitrakas](https://github.com/abhijitrakas)
* Check and verify purging is enabled before purging cache. [#168](https://github.com/rtCamp/nginx-helper/pull/168) - by [jaredwsmith](https://github.com/jaredwsmith)
* Hide Purge Cache button in admin bar …
=> Version Update 2.2.0

admin/class-nginx-helper-admin.php
Adding this hook allow to call a function after purge_all was called without distinction between FastCGI, Redis or Predis.
=> Add hook to fire purge_all for any caching type

admin/partials/nginx-helper-general-options.php
This PR fixes #240 issue
The issue was in array from which we recieve "purge_url" value. It was `$nginx_helper_admin->options` which store previous values. I've changed it to `nginx_helper_settings` which is used for all other fields.
=> Changed variable for 'Custom Purge URL' field value

admin/class-purger.php
Fixes #190 & #251
Check if `$url_data['path']` is defined to fix notices thrown when invalidating the home page
> PHP Notice:  Undefined index: path in /wp-content/plugins/nginx-helper/admin/class-purger.php on line 390
=> Fix PHP Notice:  Undefined index: path

admin/partials/nginx-helper-general-options.php
PHP throws a warning at fopen line that it failed to open log file. This
happens when program tries to create a file but parent directory is not
writable.
This commit adds that check before attempting creation of a file
=> Attempt log file creation if parent directory is writable

admin/class-nginx-helper-admin.php
Do not need to purge the homepage, date archive, author archive, category archive on the update of each menu item. Purging those URLs on each menu item update will cause performance issues and overhead. So, this PR will ignore purging on `nav_menu_item`.
See #112
=> Fix: ignore purging on update of every nav_menu_item

admin/class-nginx-helper-admin.php, admin/partials/nginx-helper-admin-display.php, admin/partials/nginx-helper-general-options.php
Fixes PHP 8.1 compatibility issues and few phpcs.
https://github.com/rtCamp/nginx-helper/issues/291
=> Fix PHP 8.1 compatibility issues and phpcs

admin/partials/nginx-helper-general-options.php
- This PR adds functionality to re-populate the empty text input fields with their default values at the time of save. 
- This will ensure that we will never have any empty text input field & will never get a fatal error due to an empty text input field.
- https://github.com/rtCamp/nginx-helper/issues/333
=> GH-333: Fatal Error on Empty Redis Port Setting in Nginx Helper Plugin [Develop]

Development.md
The aim of this PR is to add a Development.md file.
- Documentation
The development processes are contained in a file called Development.md that is located in the root folder.
=> Add Development.MD file.

Development.md
The aim of this PR is to add a Development.md file.
- Documentation
The development processes are contained in a file called Development.md that is located in the root folder.
=> Add Development.md file

admin/class-nginx-helper-admin.php, includes/class-nginx-helper.php
The aim of this PR is to fix the warning in WordPress 6.7 since the i18n functions were being invoked before the init hook was fired.
- Bug Fix
- https://github.com/rtCamp/nginx-helper/issues/364
- Upgrade your WordPress to version 6.7
- Open the Nginx Helper Options Page.
- Install a non-English language translation for the plugin.
- Set the site language as the one selected above.
- Once you are on admin dashboard, ensure that there are no warnings displayed.
Example to install a non-English Language:
`wp language plugin install nginx-helper ru_RU` // Install the Russian Language translation.
`wp user meta update 1 locale ru_RU` // Change the current user language to russian.
=> Fix _load_textdomain_just_in_time notice in WordPress 6.7

README.md, readme.txt
- Added documentation on the usage of redis constants for database, username, password.
- Added documentation on modifying the nginx helper options using WP-CLI.
=> Add the FAQ for new Redis Constants

admin/class-predis-purger.php
The aim of this PR is to handle the exception when the database number for Predis is out of bounds.
- Bug Fix
- https://github.com/rtCamp/nginx-helper/issues/350
The code has been tested locally and is working as expected.
=> Handle Predis Exception when Database is Out of Bounds.

admin/class-fastcgi-purger.php
This PR resolves the issue #396.
Original PR - https://github.com/rtCamp/nginx-helper/pull/397
=> fix: FastCGI AMP purge when purge_method=unlink_files

admin/partials/nginx-helper-sidebar-display.php
fixes #358 
This PR replaces links in the `Useful Links` Section with updated ones
=> Replace broken links in useful links  section

README.md, includes/class-nginx-helper.php, readme.txt
The aim of this PR is to add a filter to read the cache path for nginx. It allows for setting custom paths for the plugin.
- New Feature
https://github.com/rtCamp/nginx-helper/issues/298
The code has been tested locally and is working as expected.
=> Add a Filter to allow modifying the cache path for Nginx [Master]

admin/class-purger.php
Why? : the _purge_personal_urls() func was working on an option called purgeable_url which is not set anywhere in the options
=> Remove purge_personal_urls functions

includes/class-nginx-helper-deactivator.php
- Remove the version option from DB on plugin uninstall.
Ref: https://github.com/rtCamp/nginx-helper/issues/431
=> Remove Version option from DB on deactivate

README.md, admin/class-nginx-helper-admin.php, admin/partials/nginx-helper-general-options.php, admin/partials/nginx-helper-sidebar-display.php, includes/class-nginx-helper.php, readme.txt
This PR adds a mechanism to suggest or automatically purge cache after WordPress core, a plugin, or a theme updates.
- By default, auto-purge is disabled.
- Developers can enable it via the filter:
`add_filter( 'rt_wp_nginx_helper_enable_auto_purge_on_any_update', '__return_true' );`
- If auto-purge is disabled (default), the plugin shows an admin notice prompting users to purge the cache manually after an update.
- Dismissing the notice or performing a purge clears the notice.
- The settings page displays a disabled checkbox showing the current auto-purge status and instructions regarding the filter.
Closes:- [WordPress Support Thread](https://wordpress.org/support/topic/auto-purge-option-having-issue-with-slider-revolution/)
- To ensure users’ sites always reflect the latest changes …
=> Add Auto-Purge Suggestion After WordPress Core, Plugin, or Theme Updates [develop]

Development.md
- Minor doc update to fix the URL pointing to the updated URL for installation guide. 
- This is the new URL `https://easyengine.io/cli/handbook/install/`
=> Docs: Update the instructions for installation guide in the `development.md`

Development.md
- Minor doc update to fix the URL pointing to the updated URL for installation guide.
- This is the new URL https://easyengine.io/cli/handbook/install/
=> Docs: Update the instructions for installation guide in the development.md [master]

README.md, admin/class-nginx-helper-admin.php, admin/partials/nginx-helper-general-options.php, admin/partials/nginx-helper-sidebar-display.php, includes/class-nginx-helper.php, readme.txt
This PR adds a mechanism to suggest or automatically purge cache after WordPress core, a plugin, or a theme updates.
- By default, auto-purge is disabled.
- Developers can enable it via the filter:
`add_filter( 'rt_wp_nginx_helper_enable_auto_purge_on_any_update', '__return_true' );`
- If auto-purge is disabled (default), the plugin shows an admin notice prompting users to purge the cache manually after an update.
- Dismissing the notice or performing a purge clears the notice.
- The settings page displays a disabled checkbox showing the current auto-purge status and instructions regarding the filter.
Closes:- [WordPress Support Thread](https://wordpress.org/support/topic/auto-purge-option-having-issue-with-slider-revolution/)
- To ensure users’ sites always reflect the latest changes …
=> Add Auto-Purge Suggestion After WordPress Core, Plugin, or Theme Updates [master]
